Repository astrostat/pylira, pull requests merged in 2021-11, with the labels that each got.

#4 Add Python 3.9 to test environments
  tox.ini
Labels: infrastructure

#5 Add instructions to create developer environment
  docs/index.rst
  docs/pylira/developer.rst
  docs/pylira/index.rst
Labels: documentation

#6 Add pybind 11 struct example and tests
  pylira/__init__.py
  pylira/src/lira.cpp
  pylira/tests/test_core.py
Labels: infrastructure

#7 Add minimal numpy example using pybind vectorize
  pylira/src/lira.cpp
  pylira/tests/test_core.py
Labels: infrastructure

#8 Add minimal numpy wrapper example #2
  pylira/__init__.py
  pylira/src/lira.cpp
  pylira/tests/test_core.py
Labels: infrastructure

#9 Split Python bindings from source code
  MANIFEST.in
  pylira/src/lira.h
  pylira/src/lirabind.cpp
  setup.py
Labels: infrastructure

#10 Add lira code base
  .github/workflows/ci_tests.yml
  pylira/__init__.py
  pylira/src/lira.h
  pylira/src/lirabind.cpp
  pylira/tests/test_core.py
  setup.py
Labels: infrastructure

#11 Use clang format to format C code
  .clang-format
  docs/pylira/developer.rst
  pylira/src/lira.h
  pylira/src/lirabind.cpp
Labels: infrastructure

#12 Add simple test dataset
  docs/conf.py
  docs/index.rst
  docs/pylira/data.rst
  pylira/data/__init__.py
  pylira/data/core.py
  pylira/tests/test_core.py
  pylira/utils/plot.py
  setup.cfg
Labels: documentation, enhancement, infrastructure

#13 Implement LIRADeconvolver class
  pylira/__init__.py
  pylira/core.py
  pylira/tests/test_core.py
  pylira/utils/plot.py
Labels: enhancement

#14 Add LIRADeconvolver docstring example
  docs/pylira/index.rst
  pylira/__init__.py
  pylira/core.py
Labels: documentation

#15 Removes seg fault-causing R functions from LIRA C code
  pylira/core.py
  pylira/data/core.py
  pylira/src/lira.h
  pylira/src/lirabind.cpp
  pylira/tests/test_core.py
Labels: bug

#23 Add disk source test dataset
  .gitignore
  docs/pylira/data.rst
  pylira/data/core.py
  pylira/data/tests/__init__.py
  pylira/data/tests/test_core.py
  pylira/tests/test_core.py
Labels: enhancement

#24 Implement gauss and point sources test data
  docs/pylira/data.rst
  pylira/data/core.py
  pylira/data/tests/test_core.py
  pylira/tests/test_core.py
  pylira/utils/plot.py
Labels: documentation, enhancement

#25 Add parameter trace asserts
  pylira/tests/test_core.py
Labels: enhancement

#27 Add trace result and plotting
  pylira/utils/plot.py
  pylira/utils/tests/test_plot.py
Labels: enhancement

#28 Expose fit background scale parameter
  pylira/core.py
  pylira/src/lirabind.cpp
  pylira/tests/test_core.py
Labels: enhancement

#29 Add function to plot parameter distributions
  pylira/utils/plot.py
  pylira/utils/tests/test_plot.py
Labels: enhancement

#30 Add trace table to Deconvolver result
  pylira/core.py
  pylira/tests/test_core.py
  pylira/utils/plot.py
Labels: enhancement

#31 Implement LIRADeconvolverResult object
  pylira/core.py
  pylira/tests/test_core.py
Labels: enhancement

#32 Implement result FITS serialization
  pylira/core.py
  pylira/tests/test_core.py
  pylira/utils/io.py
Labels: enhancement

#33 Implement result FITS serialization read
  pylira/__init__.py
  pylira/core.py
  pylira/tests/test_core.py
  pylira/utils/io.py
Labels: enhancement

#34 Exposure plotting on result object
  pylira/core.py
  pylira/tests/test_core.py
  pylira/utils/io.py
  pylira/utils/plot.py
Labels: enhancement

#35 Implement pixel trace plotting
  pylira/core.py
  pylira/utils/plot.py
  pylira/utils/tests/test_plot.py
Labels: enhancement

#37 Add LIRADeconvolver.__str__
  pylira/core.py
  pylira/tests/test_core.py
  pylira/utils/plot.py
Labels: enhancement
